name: Check Version Increment

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

jobs:
  check:
    if: github.base_ref == 'release' && github.head_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: pr

      - name: Grant gradle permissions
        run: chmod +x ./gradlew

      - name: Compare versions
        run: |
          BASE_VERSION=$(cd base && ./gradlew printVersion -q)
          PR_VERSION=$(cd pr && ./gradlew printVersion -q)
          
          echo "Base version: $BASE_VERSION"
          echo "PR version: $PR_VERSION"
          
          if [ "$BASE_VERSION" == "$PR_VERSION" ]; then
            echo "Version has not been changed."
            exit 1
          fi